title: Jorid Jønland's Portfolio Site
author: Jorid Jønland
email: jorid@jonland.io
description: >-
  Jorid Jønland: Playable Experience Designer and all-round nerd
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io
logo: "/uploads/2018/09/04/boldsignature-2.png"
navigation:
  - link: "/"
    link_text: home
  - link: "/portfolio"
    link_text: portfolio
  - link: "/contact"
    link_text: get in touch

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post-default"
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
