---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- type: text
  name: heading
  label: Heading
- type: textarea
  name: body
  label: Body
  config:
    wysiwyg: true
    schema:
      format: markdown
pages:
- _posts/pilgrims.md
