---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- type: text
  name: heading
  label: Heading
pages:
- _posts/2018-09-08-pilgrims.md
